/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PathInTabTitlePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var UPDATE_TITLE_INTERVAL_MS = 2e3;
var UPDATE_TITLE_MIN_DELAY_MS = 150;
var PathInTabTitlePlugin = class extends import_obsidian.Plugin {
  updateTabTitle() {
    const file = this.app.workspace.getActiveFile();
    const filePath = file == null ? void 0 : file.path;
    if (!filePath) {
      return;
    }
    const tabTitleElement = document.querySelector(".workspace-tabs.mod-active .workspace-tab-header.is-active .workspace-tab-header-inner-title");
    if (!tabTitleElement) {
      return;
    }
    const filePathEnd = file.path.split("/").slice(-2).join("/");
    const filePathEndWithoutExtension = filePathEnd.replace(/\.md$/, "");
    const tabTitleParts = filePathEndWithoutExtension.split("/").reverse();
    const fileName = tabTitleParts[0];
    const folderName = tabTitleParts[1];
    let newTabTitleHtml = fileName ? `<span>${fileName}</span>` : "";
    const folderText = ` | ${folderName}`;
    if (folderName) {
      newTabTitleHtml += ` <small>${folderText}</small>`;
    }
    if (tabTitleElement.innerHTML != newTabTitleHtml) {
      tabTitleElement.innerHTML = "";
      if (fileName) {
        tabTitleElement.createSpan({ text: fileName });
      }
      if (folderName) {
        tabTitleElement.createEl("small", { text: folderText });
      }
    }
  }
  updateTabTitleDelayed() {
    window.setTimeout(() => {
      this.updateTabTitle();
    }, UPDATE_TITLE_MIN_DELAY_MS);
  }
  async onload() {
    this.updateTabTitleDelayed();
    this.intervalUpdateTitle = window.setInterval(
      () => {
        this.updateTabTitle();
      },
      UPDATE_TITLE_INTERVAL_MS
    );
    this.registerEvent(this.app.workspace.on("layout-change", () => {
      this.updateTabTitleDelayed();
    }));
    this.registerEvent(this.app.workspace.on("file-open", () => {
      this.updateTabTitleDelayed();
    }));
    this.registerEvent(this.app.workspace.on("window-open", () => {
      this.updateTabTitleDelayed();
    }));
    this.registerInterval(this.intervalUpdateTitle);
  }
  onunload() {
    if (this.intervalUpdateTitle) {
      clearInterval(this.intervalUpdateTitle);
    }
  }
};
