/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PathInTabTitlePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var UPDATE_TITLE_INTERVAL_MS = 2e3;
var UPDATE_TITLE_MIN_DELAY_MS = 150;
var PathInTabTitlePlugin = class extends import_obsidian.Plugin {
  getFolderText(folderName) {
    return ` | ${folderName}`;
  }
  getTabTitleRenderInfo() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      return null;
    }
    const filePathEnd = file.path.split("/").slice(-2).join("/");
    const filePathEndWithoutExtension = filePathEnd.replace(/\.md$/, "");
    const tabTitleParts = filePathEndWithoutExtension.split("/").reverse();
    const fileName = tabTitleParts[0];
    const folderName = tabTitleParts[1];
    let newTabTitleHtml = fileName ? `<span>${fileName}</span>` : "";
    const folderText = folderName ? ` | ${folderName}` : "";
    if (folderName) {
      newTabTitleHtml += ` <small>${folderText}</small>`;
    }
    return {
      folderText,
      newTabTitleHtml,
      fileName
    };
  }
  getTabTitleElement() {
    return activeDocument.querySelector(".workspace-tabs.mod-active .workspace-tab-header.is-active .workspace-tab-header-inner-title");
  }
  updateTabTitle() {
    let renderInfo = this.getTabTitleRenderInfo();
    let tabTitleElement = this.getTabTitleElement();
    if (!renderInfo || !tabTitleElement) {
      return;
    }
    if (tabTitleElement.innerHTML != renderInfo.newTabTitleHtml) {
      let updateTimeout = 0;
      if (tabTitleElement.innerHTML) {
        updateTimeout = 50;
      }
      activeWindow.setTimeout(() => {
        const renderInfoCurrent = this.getTabTitleRenderInfo();
        const tabTitleElementCurrent = this.getTabTitleElement();
        if (!renderInfoCurrent || !tabTitleElementCurrent) {
          return;
        }
        if (tabTitleElementCurrent.innerHTML) {
          tabTitleElementCurrent.innerHTML = "";
        }
        let renderInfo2 = this.getTabTitleRenderInfo();
        let tabTitleElement2 = this.getTabTitleElement();
        if (!renderInfo2 || !tabTitleElement2) {
          return;
        }
        if (renderInfo2.fileName) {
          tabTitleElement2.createSpan({ text: renderInfo2.fileName });
        }
        if (renderInfo2.folderText) {
          tabTitleElement2.createEl("small", { text: renderInfo2.folderText });
        }
        console.error("__TEST__ d9k 150: tab title updated");
      }, updateTimeout);
    }
  }
  updateTabTitleDelayed() {
    activeWindow.setTimeout(() => {
      this.updateTabTitle();
    }, UPDATE_TITLE_MIN_DELAY_MS);
  }
  async onload() {
    this.updateTabTitleDelayed();
    this.intervalUpdateTitle = activeWindow.setInterval(
      () => {
        this.updateTabTitle();
      },
      UPDATE_TITLE_INTERVAL_MS
    );
    this.registerEvent(this.app.workspace.on("layout-change", () => {
      this.updateTabTitleDelayed();
    }));
    this.registerEvent(this.app.workspace.on("file-open", () => {
      this.updateTabTitleDelayed();
    }));
    this.registerEvent(this.app.workspace.on("window-open", () => {
      this.updateTabTitleDelayed();
    }));
    this.registerInterval(this.intervalUpdateTitle);
  }
  onunload() {
    if (this.intervalUpdateTitle) {
      activeWindow.clearInterval(this.intervalUpdateTitle);
    }
  }
};
